name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run linter (if available)
        run: |
          if [ -f "package.json" ] && grep -q '"lint"' package.json; then
            pnpm run lint
          else
            echo "No lint script found, skipping..."
          fi
        continue-on-error: false

      - name: Run type check (if available)
        run: |
          if [ -f "package.json" ] && grep -q '"check"' package.json; then
            pnpm run check
          else
            echo "No type check script found, skipping..."
          fi
        continue-on-error: false

      - name: Run tests (if available)
        run: |
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            pnpm run test
          else
            echo "No test script found, skipping..."
          fi

      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Check build output
        run: |
          if [ -d "build" ]; then
            echo "Build directory exists"
            ls -la build/
          else
            echo "Build directory not found"
            exit 1
          fi
