name: Deploy Sanity Studio

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      SANITY_DEPLOY_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
      SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
      SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm --version

      - name: Install deps (studio)
        working-directory: studio
        run: pnpm install --frozen-lockfile

      - name: Check required tokens
        run: |
          if [ -n "${SANITY_AUTH_TOKEN}" ] || [ -n "${SANITY_DEPLOY_TOKEN}" ] || [ -n "${SANITY_API_TOKEN}" ] || [ -n "${SANITY_WRITE_TOKEN}" ]; then
            exit 0
          fi
          echo "Sanity deploy token is not configured (SANITY_AUTH_TOKEN / SANITY_DEPLOY_TOKEN / SANITY_API_TOKEN / SANITY_WRITE_TOKEN のいずれかを設定してください)" >&2
          exit 1

      - name: Deploy Sanity Studio from repo config
        run: node scripts/deploy-sanity-studio.mjs

